version: '3'

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    command: npm run serve
    ports:
      - 3000:8080
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src

  api:
    command: npm run start:dev
    ports:
      - 3001:3001
    environment:
      - APP_ENV=dev
    volumes:
    - ./api:/usr/src/app

  html-api:
    command: npm run dev
    ports:
      - 3002:3002
    volumes:
    - ./html-api:/usr/src/app

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=api-db
    depends_on:
      - api-db
    networks:
      - vdomkota-service-network
