version: '3'

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    container_name: vdomkota-docker-frontend
    restart: unless-stopped
    command: serve -s build -l 3000
    networks:
      - vdomkota-service-network

  api:
    build: ./api
    container_name: vdomkota-docker-api
    command: npm run start:prod
    restart: unless-stopped
    environment:
      - APP_PORT=3001
      - MONGODB_HOST=api-db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=vdomkota
      - APP_ENV=prod
    depends_on:
      - api-db
    networks:
      - vdomkota-service-network

  api-db:
    image: mongo:latest
    container_name: vdomkota-docker-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - vdomkota-service-network

  html-api:
    build: ./html-api
    container_name: vdomkota-docker-html-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3002
      - API_URL=http://api:3001/
    networks:
      - vdomkota-service-network

  nginx:
    image: nginx:stable-alpine
    container_name: vdomkota-docker-nginx
    ports:
      - 80:80
    volumes:
    - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    - ./static/:/usr/share/nginx/static
    depends_on:
      - html-api
      - api
      - frontend
    links:
      - html-api:html-api
      - api:api
      - frontend:frontend
    networks:
      - vdomkota-service-network

volumes:
  mongodb_api:

networks:
  vdomkota-service-network:
    driver: bridge
