version: '3'

services:
  api:
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
    - ./api:/usr/src/app

  html-api:
    command: npm run dev
    volumes:
    - ./html-api:/usr/src/app

  nginx:
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
