version: '3'

services:
  api:
    command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      - APP_ENV=dev
    volumes:
    - ./api:/usr/src/app

  html-api:
    command: npm run dev
    volumes:
    - ./html-api:/usr/src/app

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=api-db
    depends_on:
      - api-db
    networks:
      - vdomkota-service-network
